import Sidebar from 'src/components/Sidebar/Sidebar';
import styles from './Layout.module.scss';
import Head from 'next/head';

const Layout = ({ children }) => {
  return (
    <>
      <Head>
        <title>Dashboard Next.js</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.svg" />
      </Head>

      <main className={styles.main}>
        <Sidebar />
        <section className={styles.content}>
          {children}
        </section>
      </main>
    </>
  )
}

export default Layout;